const classPhotoData = () => {
  return [
    {
      id: 6201,
      class: "A1",
      imageUrl: "assets/images/A1/Group-Photo.svg",
    },
    {
      id: 6202,
      class: "A2",
      imageUrl: "assets/images/A2/Group-Photo.svg",
    },
    {
      id: 6203,
      class: "A3",
      imageUrl: "assets/images/A3/Group-Photo.svg",
    },
    {
      id: 6204,
      class: "A4",
      imageUrl: "assets/images/A4/Group-Photo.png",
    },
    {
      id: 6205,
      class: "A5",
      imageUrl: "assets/images/A5/Group-Photo.png",
    },
    {
      id: 6206,
      class: "A6",
      imageUrl: "assets/images/A6/Group-Photo.png",
    },
    {
      id: 6207,
      class: "A7",
      imageUrl: "assets/images/A7/Group-Photo.jpg",
    },
    {
      id: 6208,
      class: "A8",
      imageUrl: "assets/images/A8/Group-Photo.jpg",
    },
    {
      id: 6209,
      class: "S1",
      imageUrl: "assets/images/S1/Group-Photo.png",
    },
    {
      id: 6210,
      class: "S2",
      imageUrl: "assets/images/S2/Group-Photo.png",
    },
  ];
};

const getStudentsData = () => {
  return [
    //IPA 1
    {
      id: 1,
      class: "A1",
      name: "Abdi Ghiffari Arifin",
      birth: "Metro, 15 August 2003",
      imageUrl: "assets/images/A1/Abdi-Ghiffari-A.png",
      instagramUrl: "https://www.instagram.com/abdighffri",
    },
    {
      id: 2,
      class: "A1",
      name: "Abigael Ludwina Kalih",
      birth: "Bandar Jaya, 27 July 2003",
      imageUrl: "assets/images/A1/Abigael-Ludwina-K.png",
      instagramUrl: "https://www.instagram.com/abigael.lk",
    },
    {
      id: 3,
      class: "A1",
      name: "Achdan Mahmud",
      birth: "Jakarta, 19 December 2002",
      imageUrl: "assets/images/A1/Achdan-Mahmud.png",
      instagramUrl: "https://www.instagram.com/achdanmhmd",
    },
    {
      id: 4,
      class: "A1",
      name: "Alvin Reihansyah Makarim",
      birth: "Bandar Lampung, 8 August 2002",
      imageUrl: "assets/images/A1/Alvin-Reihansyah-M.png",
      instagramUrl: "https://www.instagram.com/alvinreihans_",
    },
    {
      id: 5,
      class: "A1",
      name: "Alya Wardah Tamimah",
      birth: "Bandung Baru, 26 March 2003",
      imageUrl: "assets/images/A1/Alm-Alya-Wardah-T.png",
      instagramUrl: "https://www.instagram.com/alya_tamimah26",
    },
    {
      id: 6,
      class: "A1",
      name: "Amanda Nabila Aristawidya",
      birth: "Metro, 23 June 2003",
      imageUrl: "assets/images/A1/Amanda-Nabila-A.png",
      instagramUrl: "https://www.instagram.com/amandanblll",
    },
    {
      id: 7,
      class: "A1",
      name: "Branden Jaya Tivantara",
      birth: "Metro, 12 November 2003",
      imageUrl: "assets/images/A1/Branden-Jaya-T.png",
      instagramUrl: "https://www.instagram.com/brandentivantara",
    },
    {
      id: 8,
      class: "A1",
      name: "Cindy Prasetya Ningrum",
      birth: "Metro, 18 June 2002",
      imageUrl: "assets/images/A1/Cindy-Prasetya-N.png",
      instagramUrl: "https://www.instagram.com/cindy.prstyaa",
    },
    {
      id: 9,
      class: "A1",
      name: "Dewanda Asri",
      birth: "Nunggal Rejo, 20 April 2003",
      imageUrl: "assets/images/A1/Dewanda-Asri.png",
      instagramUrl: "https://www.instagram.com/dewanda.a",
    },
    {
      id: 10,
      class: "A1",
      name: "Dhea Amelia",
      birth: "Metro, 20 November 2002",
      imageUrl: "assets/images/A1/Dhea-Amelia.png",
      instagramUrl: "https://www.instagram.com/dheame20",
    },
    {
      id: 11,
      class: "A1",
      name: "Diva Naya Fadhila",
      birth: "Metro, 1 April 2003",
      imageUrl: "assets/images/A1/Diva-Naya-F.png",
      instagramUrl: "https://www.instagram.com/divanayafdl",
    },
    {
      id: 12,
      class: "A1",
      name: "Dwi Zahra Nur Afifah",
      birth: "Ngambur, 8 August 2003",
      imageUrl: "assets/images/A1/Dwi-Zahra-Nur-A.png",
      instagramUrl: "https://www.instagram.com/afifah.zhr",
    },
    {
      id: 13,
      class: "A1",
      name: "Euis Adelia Assyfa",
      birth: "Metro, 5 January 2003",
      imageUrl: "assets/images/A1/Euis-Adelia-A.png",
      instagramUrl: "https://www.instagram.com/euis_adelia",
    },
    {
      id: 14,
      class: "A1",
      name: "Febri Wirantika Rahmawati",
      birth: "Palembang, 3 February 2003",
      imageUrl: "assets/images/A1/Febri-Wirantika-R.png",
      instagramUrl: "https://www.instagram.com/rararahma_",
    },
    {
      id: 15,
      class: "A1",
      name: "Fistriawan Aldillah",
      birth: "Metro, 26 January 2003",
      imageUrl: "assets/images/A1/Fistriawan-Aldillah.png",
      instagramUrl: "https://www.instagram.com/fistriawan",
    },
    {
      id: 16,
      class: "A1",
      name: "Gusti Ayu Made Prathita Isvari",
      birth: "Metro, 13 March 2003",
      imageUrl: "assets/images/A1/Gusti-Ayu-Made-P-I.png",
      instagramUrl: "https://www.instagram.com/gustiayumpiii",
    },
    {
      id: 17,
      class: "A1",
      name: "Ikko Ahmad Zahwawi",
      birth: "Metro, 6 February 2003",
      imageUrl: "assets/images/A1/Ikko-Ahmad-Z.png",
      instagramUrl: "https://www.instagram.com/strya157",
    },
    {
      id: 18,
      class: "A1",
      name: "Muhamad Khoirul Miftakhu Falah",
      birth: "Metro, 23 October 2002",
      imageUrl: "assets/images/A1/M-Kh-M-Falah.png",
      instagramUrl: "https://www.instagram.com/muhamadkhoirul23",
    },
    {
      id: 19,
      class: "A1",
      name: "M. Rizky Asshiddiqi",
      birth: "Bandar Lampung, 10 July 2002",
      imageUrl: "assets/images/A1/M-R-Asshiddiqi.png",
      instagramUrl: "https://www.instagram.com/rizkyasdhqi",
    },
    {
      id: 20,
      class: "A1",
      name: "Mercilia Febrina",
      birth: "Metro, 10 February 2003",
      imageUrl: "assets/images/A1/Mercilia-Febrina.png",
      instagramUrl: "https://www.instagram.com/merciliacici",
    },
    {
      id: 21,
      class: "A1",
      name: "Mulya Sari Siregar",
      birth: "Dipasena, 16 June 2003",
      imageUrl: "assets/images/A1/Mulya-Sari-S.png",
      instagramUrl: "https://www.instagram.com/mulyaregars",
    },
    {
      id: 22,
      class: "A1",
      name: "Nabil Raya Amani",
      birth: "Metro, 27 September 2003",
      imageUrl: "assets/images/A1/Nabil-Raya-A.png",
      instagramUrl: "https://www.instagram.com/Nabilrayaa",
    },
    {
      id: 23,
      class: "A1",
      name: "Narisya Zahrani",
      birth: "Metro, 1 April 2003",
      imageUrl: "assets/images/A1/Narisya-Zahrani.png",
      instagramUrl: "https://www.instagram.com/narisyaaa",
    },
    {
      id: 24,
      class: "A1",
      name: "Pandu Wijaya",
      birth: "Metro, 22 August 2002",
      imageUrl: "assets/images/A1/Pandu-Wijaya.png",
      instagramUrl: "https://www.instagram.com/pandupw22",
    },
    {
      id: 25,
      class: "A1",
      name: "Paramitha Nawangsasi",
      birth: "Metro, 23 November 2002",
      imageUrl: "assets/images/A1/Paramitha-Nawangsasi.png",
      instagramUrl: "https://www.instagram.com/_nawangsasi",
    },
    {
      id: 26,
      class: "A1",
      name: "Putri Amelia",
      birth: "Metro, 25 June 2003",
      imageUrl: "assets/images/A1/Putri-Amelia.png",
      instagramUrl: "https://www.instagram.com/putri.amll",
    },
    {
      id: 27,
      class: "A1",
      name: "Putri Uswatunhasanah",
      birth: "Sukadana, 4 June 2003",
      imageUrl: "assets/images/A1/Putri-Uswatunhasanah.png",
      instagramUrl: "https://www.instagram.com/uswatunputi04",
    },
    {
      id: 28,
      class: "A1",
      name: "Qori Lutfiah S.P",
      birth: "Tulang Bawang, 18 October 2003",
      imageUrl: "assets/images/A1/Qori-Lutfiah-S-P.png",
      instagramUrl: "https://www.instagram.com/qorilutfiah.sp",
    },
    {
      id: 29,
      class: "A1",
      name: "Randra Atthariq Muchson",
      birth: "Metro, 29 April 2003",
      imageUrl: "assets/images/A1/Randra-Atthariq-M.png",
      instagramUrl: "https://www.instagram.com/Randra_atthariq",
    },
    {
      id: 30,
      class: "A1",
      name: "Rayhan Wahyu Taufiqurrahman",
      birth: "Malang, 27 April 2003",
      imageUrl: "assets/images/A1/Rayhan-Wahyu-T.png",
      instagramUrl: "https://www.instagram.com/rayhanwahyut",
    },
    {
      id: 31,
      class: "A1",
      name: "Euis Adelia Assyfa",
      birth: "Metro, 2 March 2003",
      imageUrl: "assets/images/A1/Ronna-Assyifa.png",
      instagramUrl: "https://www.instagram.com/ronasyf",
    },
    {
      id: 32,
      class: "A1",
      name: "Salis Khairunnisa",
      birth: "Metro, 8 March 2003",
      imageUrl: "assets/images/A1/Salis-Khairunnisa.png",
      instagramUrl: "https://www.instagram.com/khrnsalis__",
    },
    {
      id: 33,
      class: "A1",
      name: "Shabita Aqsha",
      birth: "Siraman, 20 June 2003",
      imageUrl: "assets/images/A1/Shabita-Aqsa.png",
      instagramUrl: "https://www.instagram.com/shabitaq",
    },
    {
      id: 34,
      class: "A1",
      name: "Vina Oktafiana",
      birth: "Metro, 12 October 2002",
      imageUrl: "assets/images/A1/Vina-Oktafiana.png",
      instagramUrl: "https://www.instagram.com/viinaokta_",
    },

    //IPA 2
    {
      id: 35,
      class: "A2",
      name: "Agra Abhinaya Paramadharma",
      birth: "Sukoharjo, 3 July 2003",
      imageUrl: "assets/images/A2/Agra-Abhinaya-P.png",
      instagramUrl: "https://www.instagram.com/boting39",
    },
    {
      id: 36,
      class: "A2",
      name: "Amanda Dyah Meilani Putri",
      birth: "Samarinda, 4 May 2003",
      imageUrl: "assets/images/A2/Amanda-Dyah-Meilani-P.png",
      instagramUrl: "https://www.instagram.com/mandadyh",
    },
    {
      id: 37,
      class: "A2",
      name: "Annisa Faradiba",
      birth: "Metro, 27 September 2003",
      imageUrl: "assets/images/A2/Annisa-Faradiba.png",
      instagramUrl: "https://www.instagram.com/faradb27_",
    },
    {
      id: 38,
      class: "A2",
      name: "Asma Putri Salsabila",
      birth: "Gedong Tataan, 31 March 2003",
      imageUrl: "assets/images/A2/Asma-Putri-Salsabila.png",
      instagramUrl: "https://www.instagram.com/bilaaps",
    },
    {
      id: 39,
      class: "A2",
      name: "Asti Wulandari",
      birth: "Metro, 4 May 2003",
      imageUrl: "assets/images/A2/Asti-Wulandari.png",
      instagramUrl: "https://www.instagram.com/astiwdr",
    },
    {
      id: 40,
      class: "A2",
      name: "Athaya Dhiya Aulia Kirana",
      birth: "Bandar Lampung, 4 November 2002",
      imageUrl: "assets/images/A2/A-D-A-Kirana.png",
      instagramUrl: "https://www.instagram.com/athykirnn",
    },
    {
      id: 41,
      class: "A2",
      name: "Bagas Satria Prabowo",
      birth: "Metro, 5 November 2001",
      imageUrl: "assets/images/A2/Bagas-Satria-P.png",
      instagramUrl: "https://www.instagram.com/gusprabowo_",
    },
    {
      id: 42,
      class: "A2",
      name: "Bagus Robianto",
      birth: "Metro, 23 April 2003",
      imageUrl: "assets/images/A2/Bagus-Robianto.png",
      instagramUrl: "https://www.instagram.com/bagus_robianto",
    },
    {
      id: 43,
      class: "A2",
      name: "Cahaya Mahatma Sembahen",
      birth: "Metro, 18 July 2003 2003",
      imageUrl: "assets/images/A2/Cahaya-Mahatma-S.png",
      instagramUrl: "https://www.instagram.com/cahaams_",
    },
    {
      id: 44,
      class: "A2",
      name: "Cahya Dwi Saputra",
      birth: "Adirejo, 31 May 2003",
      imageUrl: "assets/images/A2/Cahya-Dwi-S.png",
      instagramUrl: "https://www.instagram.com/cahya_dsa",
    },
    {
      id: 45,
      class: "A2",
      name: "Diva Arisanti Kamilaini",
      birth: "Yogyakarta, 9 May 2003",
      imageUrl: "assets/images/A2/Diva-Arisanti-K.png",
      instagramUrl: "https://www.instagram.com/divaarisanti",
    },
    {
      id: 46,
      class: "A2",
      name: "Fadhil Mukhlisin",
      birth: "Pekalongan, 11 July 2003",
      imageUrl: "assets/images/A2/Fadhil-Mukhlisin.png",
      instagramUrl: "https://www.instagram.com/fadhilmukhlisin",
    },
    {
      id: 47,
      class: "A2",
      name: "Gusti Rahmadi",
      birth: "Metro, 16 August 2002",
      imageUrl: "assets/images/A2/Gusti-Rahmadi.png",
      instagramUrl: "https://www.instagram.com/gustirahmadi16",
    },
    {
      id: 48,
      class: "A2",
      name: "Intan Zafira",
      birth: "Banjarejo, 11 July 2003",
      imageUrl: "assets/images/A2/Intan-Zafira.png",
      instagramUrl: "https://www.instagram.com/intanzvr",
    },
    {
      id: 49,
      class: "A2",
      name: "Khairunnisa Husaini",
      birth: "Metro, 30 November 2002",
      imageUrl: "assets/images/A2/Khairunnisa-Husaini.png",
      instagramUrl: "https://www.instagram.com/nisahusainii",
    },
    {
      id: 50,
      class: "A2",
      name: "Lulu Farahdina",
      birth: "Metro, 4 December 2002",
      imageUrl: "assets/images/A2/Lulu-Farahdina.png",
      instagramUrl: "https://www.instagram.com/frhdnalulu",
    },
    {
      id: 51,
      class: "A2",
      name: "Muhammad Lutfi Devendra",
      birth: "Metro, 14 October 2002",
      imageUrl: "assets/images/A2/M-Lutfi-Devendra.png",
      instagramUrl: "https://www.instagram.com/lutfidevndraa",
    },
    {
      id: 52,
      class: "A2",
      name: "Muhammad Rifki Hawari",
      birth: "Metro, 5 December 2002",
      imageUrl: "assets/images/A2/M-Rifki-Hawari.png",
      instagramUrl: "https://www.instagram.com/",
    },
    {
      id: 53,
      class: "A2",
      name: "Natasya Raqiqa",
      birth: "Metro, 12 October 2002",
      imageUrl: "assets/images/A2/Natasya-Raqiqa.png",
      instagramUrl: "https://www.instagram.com/natasyarqa",
    },
    {
      id: 54,
      class: "A2",
      name: "Nur Afifah Fauziah",
      birth: "Pekalongan, 23 April 2003",
      imageUrl: "assets/images/A2/Nur-Afifah-Fauziah.png",
      instagramUrl: "https://www.instagram.com/afifah.fah",
    },

    {
      id: 55,
      class: "A2",
      name: "Oktania Sari",
      birth: "Karangrejo, 13 October 2002",
      imageUrl: "assets/images/A2/Oktania-Sari.png",
      instagramUrl: "https://www.instagram.com/oktaniasariiiii",
    },
    {
      id: 56,
      class: "A2",
      name: "Putri Wulandari",
      birth: "Iringmulyo, 7 June 2003",
      imageUrl: "assets/images/A2/Putri-Wulandari.png",
      instagramUrl: "https://www.instagram.com/putriyaann",
    },
    {
      id: 57,
      class: "A2",
      name: "Rafi Rizha Syakhari",
      birth: "Metro, 10 December 2002",
      imageUrl: "assets/images/A2/Rafi-Rizha-S.png",
      instagramUrl: "https://www.instagram.com/rafirizha_",
    },
    {
      id: 58,
      class: "A2",
      name: "Rahmalia Permatasari",
      birth: "Metro, 31 July 2003",
      imageUrl: "assets/images/A2/Rahmalia-Permatasari.png",
      instagramUrl: "https://www.instagram.com/rahmaliaaps",
    },
    {
      id: 59,
      class: "A2",
      name: "Raina Syairani Zakia",
      birth: "Metro, 18 September 2003",
      imageUrl: "assets/images/A2/Raina-Syairani-Z.png",
      instagramUrl: "https://www.instagram.com/rainasz_",
    },
    {
      id: 60,
      class: "A2",
      name: "Reni Auliana Amri",
      birth: "Banjarejo, 10 June 2003",
      imageUrl: "assets/images/A2/Reni-Auliana-A.png",
      instagramUrl: "https://www.instagram.com/reniamr_",
    },
    {
      id: 61,
      class: "A2",
      name: "Ria Azahra",
      birth: "Metro, 32 March 2003",
      imageUrl: "assets/images/A2/Ria-Azzahra.png",
      instagramUrl: "https://www.instagram.com/riazahra03",
    },
    {
      id: 62,
      class: "A2",
      name: "Sony Kurniawan",
      birth: "Metro, 15 January 2003",
      imageUrl: "assets/images/A2/Sony-Kurniawan.png",
      instagramUrl: "https://www.instagram.com/",
    },
    {
      id: 63,
      class: "A2",
      name: "Syandina Aisyah Darma",
      birth: "Metro, 6 January 2003",
      imageUrl: "assets/images/A2/Syandina-Aisyah-R.png",
      instagramUrl: "https://www.instagram.com/syndna",
    },
    {
      id: 64,
      class: "A2",
      name: "Thoriq Mustafa Akmal",
      birth: "Metro, 11 July 2003",
      imageUrl: "assets/images/A2/Thoriq-Mustafa-A.png",
      instagramUrl: "https://www.instagram.com/oyik_11",
    },
    {
      id: 65,
      class: "A2",
      name: "Viafebyana Mariatur Rahma",
      birth: "Metro, 8 February 2003",
      imageUrl: "assets/images/A2/Viafebyana-Mariatur-R.png",
      instagramUrl: "https://www.instagram.com/viafeb_",
    },
    {
      id: 66,
      class: "A2",
      name: "Zahra Ramadhan Karizki",
      birth: "Pekalongan, 10 November 2003",
      imageUrl: "assets/images/A2/Zahra-Ramadhan-K.png",
      instagramUrl: "https://www.instagram.com/zahrakarizkii",
    },

    //IPA 3
    {
      id: 67,
      class: "A3",
      name: "A. Whisnu Shakthi Al Ghozali",
      birth: "Metro, 29 March 2003",
      imageUrl: "assets/images/A3/a-wisnu.png",
      instagramUrl: "https://www.instagram.com/whisnu_alghazali",
    },
    {
      id: 68,
      class: "A3",
      name: "Adelia Novembelina",
      birth: "Metro, 11 November 2002",
      imageUrl: "assets/images/A3/adelia.png",
      instagramUrl: "https://www.instagram.com/adedliaa.novmb",
    },
    {
      id: 69,
      class: "A3",
      name: "Adella Shalsabila",
      birth: "Batanghari, 26 June 2003",
      imageUrl: "assets/images/A3/adella.png",
      instagramUrl: "https://www.instagram.com/adellash_",
    },
    {
      id: 70,
      class: "A3",
      name: "Adi Prasetya",
      birth: "Sukoharjo, 4 October 2002",
      imageUrl: "assets/images/A3/adi.png",
      instagramUrl: "https://www.instagram.com/atya.rog",
    },
    {
      id: 71,
      class: "A3",
      name: "Adilah Putri Sandaria",
      birth: "Metro, 15 April 2003",
      imageUrl: "assets/images/A3/Adilah.png",
      instagramUrl: "https://www.instagram.com/adilahsndaria",
    },
    {
      id: 72,
      class: "A3",
      name: "Agung Abdul Aziz",
      birth: "Yosodadi, 20 February 2003",
      imageUrl: "assets/images/A3/agung.png",
      instagramUrl: "https://www.instagram.com/abdl_aziz20",
    },
    {
      id: 73,
      class: "A3",
      name: "Akbar Deanova",
      birth: "Pringsewu, 16 Desember 2002",
      imageUrl: "assets/images/A3/akbar.png",
      instagramUrl: "https://www.instagram.com/akbardean6",
    },
    {
      id: 74,
      class: "A3",
      name: "Althorik Divano Afta",
      birth: "Metro, 16 March 2003",
      imageUrl: "assets/images/A3/althorik.png",
      instagramUrl: "https://www.instagram.com/althorikdvnaft",
    },
    {
      id: 75,
      class: "A3",
      name: "Amanda Puspita Sari",
      birth: "Metro, 7 September 2003",
      imageUrl: "assets/images/A3/amanda.png",
      instagramUrl: "https://www.instagram.com/mnda_79",
    },
    {
      id: 76,
      class: "A3",
      name: "Amanda Putri Lestari",
      birth: "Metro, 2 May 2003",
      imageUrl: "assets/images/A3/amanda-putri.png",
      instagramUrl: "https://www.instagram.com/amandapl2503",
    },
    {
      id: 77,
      class: "A3",
      name: "An-nisa Nuwayar Az-zahra",
      birth: "Metro, 30 May 2003",
      imageUrl: "assets/images/A3/an-nisa.png",
      instagramUrl: "https://www.instagram.com/an.azza",
    },
    {
      id: 78,
      class: "A3",
      name: "Aryani Nurjanah",
      birth: "Karang Baru, 28 March 2003",
      imageUrl: "assets/images/A3/aryani.png",
      instagramUrl: "https://www.instagram.com/aryaninurjnh",
    },
    {
      id: 79,
      class: "A3",
      name: "Berlian Benteng",
      birth: "Metro, 14 March 2003",
      imageUrl: "assets/images/A3/berlian.png",
      instagramUrl: "https://www.instagram.com/berlian.benteng.03",
    },
    {
      id: 80,
      class: "A3",
      name: "Citra Oktaviana Aulia",
      birth: "Metro, 28 October 2003",
      imageUrl: "assets/images/A3/citra.png",
      instagramUrl: "https://www.instagram.com/ctrra_oa",
    },
    {
      id: 81,
      class: "A3",
      name: "Cynthia Maharani",
      birth: "Bandar Lampung, 21 October 2003",
      imageUrl: "assets/images/A3/cynthia.png",
      instagramUrl: "https://www.instagram.com/cynthiamhrnii",
    },
    {
      id: 82,
      class: "A3",
      name: "Dimas Azi Rajab Aizar",
      birth: "Metro, 24 September 2003",
      imageUrl: "assets/images/A3/dimas.png",
      instagramUrl: "https://www.instagram.com/dimas_azi24",
    },
    {
      id: 83,
      class: "A3",
      name: "Althorik Divano Afta",
      birth: "Metro, 16 March 2003",
      imageUrl: "assets/images/A3/althorik.png",
      instagramUrl: "https://www.instagram.com/althorikdvnaft",
    },
    {
      id: 84,
      class: "A3",
      name: "Dzaky Raihan Cahyadi",
      birth: "Metro, 22 June 2003",
      imageUrl: "assets/images/A3/dzaky.png",
      instagramUrl: "https://www.instagram.com/raihan.cahyadi",
    },
    {
      id: 85,
      class: "A3",
      name: "Fahri Hidayat",
      birth: "Metro, 4 January 2003",
      imageUrl: "assets/images/A3/fahri.png",
      instagramUrl: "https://www.instagram.com/fahrikudo",
    },
    {
      id: 86,
      class: "A3",
      name: "Fanny Yudis Tiara Effendi",
      birth: "Metro, 1 July 2003",
      imageUrl: "assets/images/A3/fanny.png",
      instagramUrl: "https://www.instagram.com/panniiye",
    },
    {
      id: 87,
      class: "A3",
      name: "Frisca Arlyne Paulinanta Kusno",
      birth: "Simpang Luas, 18 July 2004",
      imageUrl: "assets/images/A3/frisca.png",
      instagramUrl: "https://www.instagram.com/f.arlynee",
    },
    {
      id: 88,
      class: "A3",
      name: "Gadis Tara Tantri Wjaya",
      birth: "Metro, 19 October 2003",
      imageUrl: "assets/images/A3/gadis.png",
      instagramUrl: "https://www.instagram.com/Gdistrtntri_",
    },
    {
      id: 89,
      class: "A3",
      name: "Inas Safitri",
      birth: "Metro, 21 Oktober 2002",
      imageUrl: "assets/images/A3/inas.png",
      instagramUrl: "https://www.instagram.com/inassafitri_",
    },
    {
      id: 90,
      class: "A3",
      name: "M. Rizki Darmawan",
      birth: "Metro, 20 June 2003",
      imageUrl: "assets/images/A3/m-rizki.png",
      instagramUrl: "https://www.instagram.com/kide20_",
    },
    {
      id: 91,
      class: "A3",
      name: "Mario Marceellino",
      birth: "Metro, 18 May 2003",
      imageUrl: "assets/images/A3/mario.png",
      instagramUrl: "https://www.instagram.com/Marcell.18",
    },
    {
      id: 92,
      class: "A3",
      name: "Muhammad Tristan",
      birth: "Hargomulyo, 1 August 2002",
      imageUrl: "assets/images/A3/m-tristan.png",
      instagramUrl: "https://www.instagram.com/mtristan68",
    },
    {
      id: 93,
      class: "A3",
      name: "Muhammad Tuhfa Fazeela",
      birth: "Metro, 21 August 2003",
      imageUrl: "assets/images/A3/m-tuhfa.png",
      instagramUrl: "https://www.instagram.com/tuhfaker",
    },
    {
      id: 94,
      class: "A3",
      name: "Muthiatunni'mah F. Masda",
      birth: "Karanganyar, 6 December 2002",
      imageUrl: "assets/images/A3/masda.png",
      instagramUrl: "https://www.instagram.com/muthia_masda",
    },
    {
      id: 95,
      class: "A3",
      name: "Nabila Hilmi Aziz",
      birth: "Bandarjaya, 26 August 2003",
      imageUrl: "assets/images/A3/nabila.png",
      instagramUrl: "https://www.instagram.com/nabillbox",
    },
    {
      id: 96,
      class: "A3",
      name: "Najwa Diva Novaraine",
      birth: "Metro, 8 November 2003",
      imageUrl: "assets/images/A3/najwa.png",
      instagramUrl: "https://www.instagram.com/njthemenace",
    },
    {
      id: 97,
      class: "A3",
      name: "Pandu Putra Mulwanda",
      birth: "Sidomulyo, 14 June 2002",
      imageUrl: "assets/images/A3/pandu.png",
      instagramUrl: "https://www.instagram.com/pandu_p.m",
    },
    {
      id: 98,
      class: "A3",
      name: "Rafly Alvaridzi",
      birth: "Banarjoyo, 17 June 2004",
      imageUrl: "assets/images/A3/rafly.png",
      instagramUrl: "https://www.instagram.com/bewpabler",
    },
    {
      id: 99,
      class: "A3",
      name: "Rara Maharani Bintang Lampung",
      birth: "Metro, 25 September 2003",
      imageUrl: "assets/images/A3/rara.png",
      instagramUrl: "https://www.instagram.com/raraaskyy",
    },
    {
      id: 100,
      class: "A3",
      name: "Syanindita Lulu Ramadhani",
      birth: "Raman Utara, 10 November 2002",
      imageUrl: "assets/images/A3/syanindita.png",
      instagramUrl: "https://www.instagram.com/s.dita_lr",
    },
    {
      id: 101,
      class: "A3",
      name: "Yardan Permata Nurhadian",
      birth: "Metro, 7 March 2003",
      imageUrl: "assets/images/A3/yardan.png",
      instagramUrl: "https://www.instagram.com/yardannh",
    },

    //IPA 4
    {
      id: 102,
      class: "A4",
      name: "Adriyuanto Wicaksono",
      birth: "Metro, 5 February 2003",
      imageUrl: "assets/images/A4/adriyuanto.png",
      instagramUrl: "https://www.instagram.com/adriyuanto24",
    },
    {
      id: 103,
      class: "A4",
      name: "Aisyah Rahmadini Putri",
      birth: "Metro, 30 November 2002",
      imageUrl: "assets/images/A4/aisyah.png",
      instagramUrl: "https://www.instagram.com/aisyahrahmadiniiputri",
    },
    {
      id: 104,
      class: "A4",
      name: "Akhsal Akshashila Syarief",
      birth: "Metro, 21 April 2003",
      imageUrl: "assets/images/A4/akshal.png",
      instagramUrl: "https://www.instagram.com/akshalsyarief",
    },
    {
      id: 105,
      class: "A4",
      name: "Alif Fakhri Muhammad",
      birth: "Metro, 10 July 2003",
      imageUrl: "assets/images/A4/alif.png",
      instagramUrl: "https://www.instagram.com/alif_fakhri03",
    },
    {
      id: 106,
      class: "A4",
      name: "Almira Shafira Diani",
      birth: "Metro, 20 February 2003",
      imageUrl: "assets/images/A4/almira.png",
      instagramUrl: "https://www.instagram.com/almiradiani",
    },
    {
      id: 107,
      class: "A4",
      name: "Amilati Kaisa Arom",
      birth: "Metro, 25 November 2002",
      imageUrl: "assets/images/A4/amilati.png",
      instagramUrl: "https://www.instagram.com/amilatikaiisa",
    },
    {
      id: 108,
      class: "A4",
      name: "Archimaya Mudrikaryani",
      birth: "Metro, 25 July 2003",
      imageUrl: "assets/images/A4/archimaya.png",
      instagramUrl: "https://www.instagram.com/archi_mm365",
    },
    {
      id: 109,
      class: "A4",
      name: "Aura Ayu Arlelya",
      birth: "Rukti Sedyo, 29 December 2002",
      imageUrl: "assets/images/A4/aura.png",
      instagramUrl: "https://www.instagram.com/aureell._",
    },
    {
      id: 110,
      class: "A4",
      name: "Aziza Ramadhani",
      birth: "Metro, 5 November 2003",
      imageUrl: "assets/images/A4/aziza-r.png",
      instagramUrl: "https://www.instagram.com/azizarmdn",
    },
    {
      id: 111,
      class: "A4",
      name: "Azizah Ahsaninnisa",
      birth: "Metro, 5 February 2003",
      imageUrl: "assets/images/A4/azizah.png",
      instagramUrl: "https://www.instagram.com/azizahsans",
    },
    {
      id: 112,
      class: "A4",
      name: "Citra Maharani Putri",
      birth: "Metro, 27 March 2003",
      imageUrl: "assets/images/A4/citra.png",
      instagramUrl: "https://www.instagram.com/",
    },
    {
      id: 113,
      class: "A4",
      name: "Destri Vonica Maharani",
      birth: "Banjarejo, 14 December 2002",
      imageUrl: "assets/images/A4/destri.png",
      instagramUrl: "https://www.instagram.com/desran_vm",
    },
    {
      id: 114,
      class: "A4",
      name: "Dimas Riski Kurniawan",
      birth: "Metro, 15 December 2002",
      imageUrl: "assets/images/A4/dimas.png",
      instagramUrl: "https://www.instagram.com/_mdarianti",
    },
    {
      id: 115,
      class: "A4",
      name: "Doddy August Pratama",
      birth: "Karang Rejo, 11 Desember 2002",
      imageUrl: "assets/images/A4/doddy.png",
      instagramUrl: "https://www.instagram.com/doddypratama_",
    },
    {
      id: 116,
      class: "A4",
      name: "Fatiya Syafa Azizah",
      birth: "Metro, 6 May 2003",
      imageUrl: "assets/images/A4/fatiya.png",
      instagramUrl: "https://www.instagram.com/syifaazh._",
    },
    {
      id: 117,
      class: "A4",
      name: "Galang Fajar Kusuma P.",
      birth: "Metro, 6 March 2003",
      imageUrl: "assets/images/A4/galang.png",
      instagramUrl: "https://www.instagram.com/_glngfjr",
    },
    {
      id: 118,
      class: "A4",
      name: "Goby Dewa Albani",
      birth: "Menggala, 4 November 2002",
      imageUrl: "assets/images/A4/goby.png",
      instagramUrl: "https://www.instagram.com/gobydewaaa",
    },
    {
      id: 119,
      class: "A4",
      name: "I Made Galih Fradiva Giantara",
      birth: "Rumbia, 13 July 2003",
      imageUrl: "assets/images/A4/i-made.png",
      instagramUrl: "https://www.instagram.com/fradiva_giantara",
    },
    {
      id: 120,
      class: "A4",
      name: "Kezia Jafena Thamrin",
      birth: "Cilacap, 29 May 2003",
      imageUrl: "assets/images/A4/kezia.png",
      instagramUrl: "https://www.instagram.com/kziajfnth",
    },
    {
      id: 121,
      class: "A4",
      name: "M. Dava Syahputra",
      birth: "Siraman, 3 March 2003",
      imageUrl: "assets/images/A4/m-dava.png",
      instagramUrl: "https://www.instagram.com/mdava_syahputra",
    },
    {
      id: 122,
      class: "A4",
      name: "Made Arianti",
      birth: "Rejo Binangun, 17 October 2002",
      imageUrl: "assets/images/A4/made-a.png",
      instagramUrl: "https://www.instagram.com/_mdarianti",
    },
    {
      id: 123,
      class: "A4",
      name: "Millifica Kirey Lantidatika",
      birth: "Metro, 13 May 2003",
      imageUrl: "assets/images/A4/millifica.png",
      instagramUrl: "https://www.instagram.com/millificakl",
    },
    {
      id: 124,
      class: "A4",
      name: "Muhammad Fakhri Rifqi",
      birth: "Metro, 29 November 2003",
      imageUrl: "assets/images/A4/m-fakhri.png",
      instagramUrl: "https://www.instagram.com/fakhririfqi",
    },
    {
      id: 125,
      class: "A4",
      name: "Nashwa Adinda A.",
      birth: "Metro, 30 May 2003",
      imageUrl: "assets/images/A4/nashwa.png",
      instagramUrl: "https://www.instagram.com/nashwaaad",
    },
    {
      id: 126,
      class: "A4",
      name: "Ni KM. Agittia Selviana Dewi",
      birth: "Metro, 22 August 2003",
      imageUrl: "assets/images/A4/komang.png",
      instagramUrl: "https://www.instagram.com/komang_selviana",
    },
    {
      id: 127,
      class: "A4",
      name: "Nisa Oda Fauzia",
      birth: "Metro, 11 September 2003",
      imageUrl: "assets/images/A4/nisa.png",
      instagramUrl: "https://www.instagram.com/nisafzaa",
    },
    {
      id: 128,
      class: "A4",
      name: "Raffles Riovaldi",
      birth: "Metro, 28 July 2003",
      imageUrl: "assets/images/A4/raffles.png",
      instagramUrl: "https://www.instagram.com/r.rvldi28",
    },
    {
      id: 129,
      class: "A4",
      name: "Rizha Riyanti",
      birth: "Metro, 10 January 2003",
      imageUrl: "assets/images/A4/rizha.png",
      instagramUrl: "https://www.instagram.com/rizhaaar",
    },
    {
      id: 130,
      class: "A4",
      name: "Shabira Khoirunnisa",
      birth: "Metro, 5 January 2003",
      imageUrl: "assets/images/A4/shabira.png",
      instagramUrl: "https://www.instagram.com/shabirakhr",
    },
    {
      id: 131,
      class: "A4",
      name: "Shefira Dwi Rizkiyanti",
      birth: "Metro, 12 March 2002",
      imageUrl: "assets/images/A4/shefira.png",
      instagramUrl: "https://www.instagram.com/fira_rzkynt",
    },
    {
      id: 132,
      class: "A4",
      name: "Sonya Hening Tyas",
      birth: "Magetan, 27 April 2003",
      imageUrl: "assets/images/A4/sonya.png",
      instagramUrl: "https://www.instagram.com/sonyatyas_",
    },
    {
      id: 133,
      class: "A4",
      name: "Steevan Urian Robiyanto",
      birth: "Metro, 22 March 2003",
      imageUrl: "assets/images/A4/steevan.png",
      instagramUrl: "https://www.instagram.com/steevan_urian",
    },
    {
      id: 134,
      class: "A4",
      name: "Syafira Elfa Ramadhan",
      birth: "Metro, 17 November 2003",
      imageUrl: "assets/images/A4/syafira.png",
      instagramUrl: "https://www.instagram.com/syfiaraael",
    },
    {
      id: 135,
      class: "A4",
      name: "Visi Hati Angellita",
      birth: "Bandar Lampung, 3 February 2003",
      imageUrl: "assets/images/A4/visi.png",
      instagramUrl: "https://www.instagram.com/visihati_",
    },
    {
      id: 136,
      class: "A4",
      name: "Wina Angelina",
      birth: "Bandar Lampung, 25 July 2002",
      imageUrl: "assets/images/A4/wina.png",
      instagramUrl: "https://www.instagram.com/winangln",
    },

    //IPA 5
    {
      id: 137,
      class: "A5",
      name: "Abdul Rahman Wahid",
      birth: "Iring Mulyo, 28 January 2003",
      imageUrl: "assets/images/A5/abdul.png",
      instagramUrl: "https://www.instagram.com/abdlrwhd",
    },
    {
      id: 138,
      class: "A5",
      name: "Abelia Chairunissa Chandra",
      birth: "Metro, 24 August 2003",
      imageUrl: "assets/images/A5/abelia.png",
      instagramUrl: "https://www.instagram.com/abeliachandra",
    },
    {
      id: 139,
      class: "A5",
      name: "Affandi Afrizal",
      birth: "Metro, 22 January 2003",
      imageUrl: "assets/images/A5/affandi.png",
      instagramUrl: "https://www.instagram.com/affandiarzl",
    },
    {
      id: 140,
      class: "A5",
      name: "Alida Reka Herdana",
      birth: "Bekasi, 3 October 2002",
      imageUrl: "assets/images/A5/alida.png",
      instagramUrl: "https://www.instagram.com/alida",
    },
    {
      id: 141,
      class: "A5",
      name: "Aliya Salma",
      birth: "Metro, 31 December 2003",
      imageUrl: "assets/images/A5/aliya.png",
      instagramUrl: "https://www.instagram.com/alyslma",
    },
    {
      id: 142,
      class: "A5",
      name: "Amalia Hakim Rahmawati",
      birth: "Metro, 16 September 2003",
      imageUrl: "assets/images/A5/amalia.png",
      instagramUrl: "https://www.instagram.com/amaliahakimm",
    },
    {
      id: 143,
      class: "A5",
      name: "Amara Chyntia Putri",
      birth: "Pekalongan, 8 August 2003",
      imageUrl: "assets/images/A5/amara.png",
      instagramUrl: "https://www.instagram.com/amaraa.cp",
    },
    {
      id: 144,
      class: "A5",
      name: "Anggie Febriyanti",
      birth: "Metro, 5 February 2003",
      imageUrl: "assets/images/A5/anggie.png",
      instagramUrl: "https://www.instagram.com/anggiynti52_",
    },
    {
      id: 145,
      class: "A5",
      name: "Anindiya Aisyah Putri",
      birth: "Metro, 8 July 2003",
      imageUrl: "assets/images/A5/anindiya.png",
      instagramUrl: "https://www.instagram.com/anindiyaap_",
    },
    {
      id: 146,
      class: "A5",
      name: "Annisa Rahmawati",
      birth: "Mekarsari, 16 June 2003",
      imageUrl: "assets/images/A5/annisa.png",
      instagramUrl: "https://www.instagram.com/ann_mnrh",
    },
    {
      id: 147,
      class: "A5",
      name: "Anselmo Bima",
      birth: "Metro, 1 July 2003",
      imageUrl: "assets/images/A5/anselmo.png",
      instagramUrl: "https://www.instagram.com/ansleeeem.00",
    },
    {
      id: 148,
      class: "A5",
      name: "Athaala Fathia",
      birth: "Kotagajah, 10 May 2003",
      imageUrl: "assets/images/A5/athaala.png",
      instagramUrl: "https://www.instagram.com/athaalafth",
    },
    {
      id: 149,
      class: "A5",
      name: "Aviliana",
      birth: "Metro, 27 January 2003",
      imageUrl: "assets/images/A5/aviliana.png",
      instagramUrl: "https://www.instagram.com/avilianaa",
    },
    {
      id: 150,
      class: "A5",
      name: "Azahra Avisa",
      birth: "Metro, 30 April 2003",
      imageUrl: "assets/images/A5/azahra.png",
      instagramUrl: "https://www.instagram.com/azahraavs",
    },
    {
      id: 151,
      class: "A5",
      name: "Depryanto Rizky Saputra",
      birth: "Metro, 7 December 2002",
      imageUrl: "assets/images/A5/depryanto.png",
      instagramUrl: "https://www.instagram.com/depry17",
    },
    {
      id: 152,
      class: "A5",
      name: "Dya Ayu Putriyana",
      birth: "Metro, 9 May 2003",
      imageUrl: "assets/images/A5/dya-ayu.png",
      instagramUrl: "https://www.instagram.com/putriyana_",
    },
    {
      id: 153,
      class: "A5",
      name: "Ega Helmi Mubarok",
      birth: "Metro, 22 July 2003",
      imageUrl: "assets/images/A5/ega.png",
      instagramUrl: "https://www.instagram.com/ega_helmi22",
    },
    {
      id: 154,
      class: "A5",
      name: "Faisal Mahdy Amanda",
      birth: "Metro, 21 January 2004",
      imageUrl: "assets/images/A5/faisal.png",
      instagramUrl: "https://www.instagram.com/faisalmahdy",
    },
    {
      id: 155,
      class: "A5",
      name: "Ghaitsa Lulua",
      birth: "Metro, 11 November 2003",
      imageUrl: "assets/images/A5/ghaitsa.png",
      instagramUrl: "https://www.instagram.com/ghaitsala",
    },
    {
      id: 156,
      class: "A5",
      name: "Guntur Setia Aji Pamungkas",
      birth: "Siraman, 21 April 2002",
      imageUrl: "assets/images/A5/guntur.png",
      instagramUrl: "https://www.instagram.com/gun_en_tur",
    },
    {
      id: 157,
      class: "A5",
      name: "Habib Abdul Rasyid",
      birth: "Metro, 12 Jnuary 2003",
      imageUrl: "assets/images/A5/habib.png",
      instagramUrl: "https://www.instagram.com/harsyid",
    },
    {
      id: 158,
      class: "A5",
      name: "Khalisah Fhadililah Zulkarnaen",
      birth: "Tangerang, 20 June 2003",
      imageUrl: "assets/images/A5/khalisah.png",
      instagramUrl: "https://www.instagram.com/khalisahfz",
    },
    {
      id: 159,
      class: "A5",
      name: "Lili Farahdina",
      birth: "Metro, 3 December 2002",
      imageUrl: "assets/images/A5/lili.png",
      instagramUrl: "https://www.instagram.com/frh.dnaa",
    },
    {
      id: 160,
      class: "A5",
      name: "M. Iqbal Abizard P.",
      birth: "Metro, 1 June 2003",
      imageUrl: "assets/images/A5/m-iqbal.png",
      instagramUrl: "https://www.instagram.com/iqballabzrd",
    },
    {
      id: 161,
      class: "A5",
      name: "Muhammad Reza Fahlefi",
      birth: "Metro, 10 May 2003",
      imageUrl: "assets/images/A5/m-reza.png",
      instagramUrl: "https://www.instagram.com/muhammadreza_fhl10",
    },
    {
      id: 162,
      class: "A5",
      name: "Nabila Nur Amaliah",
      birth: "Metro, 15 June 2003",
      imageUrl: "assets/images/A5/nabila.png",
      instagramUrl: "https://www.instagram.com/nabilaamaliahh",
    },
    {
      id: 163,
      class: "A5",
      name: "Salma Kartika Rahmalia",
      birth: "Metro, 18 April 2003",
      imageUrl: "assets/images/A5/salma.png",
      instagramUrl: "https://www.instagram.com/salmakar",
    },
    {
      id: 164,
      class: "A5",
      name: "Seni Utama A.",
      birth: "Metro, 27 June 2003",
      imageUrl: "assets/images/A5/seni.png",
      instagramUrl: "https://www.instagram.com/s.taaama",
    },
    {
      id: 165,
      class: "A5",
      name: "Shela Sandra Kirana",
      birth: "Metro, 23 June 2003",
      imageUrl: "assets/images/A5/shela.png",
      instagramUrl: "https://www.instagram.com/shelasndr",
    },
    {
      id: 166,
      class: "A5",
      name: "Winda Tiara Ahmad",
      birth: "Metro, 1 May 2002",
      imageUrl: "assets/images/A5/Winda.png",
      instagramUrl: "https://www.instagram.com/wndtr",
    },
    {
      id: 167,
      class: "A5",
      name: "Yuan Tiko",
      birth: "Metro, 11 June 2003",
      imageUrl: "assets/images/A5/yuan.png",
      instagramUrl: "https://www.instagram.com/yuantiko",
    },
    {
      id: 168,
      class: "A5",
      name: "Zefianto",
      birth: "Metro, 8 April 2003",
      imageUrl: "assets/images/A5/zefianto.png",
      instagramUrl: "https://www.instagram.com/zefi_anto",
    },
    {
      id: 169,
      class: "A5",
      name: "Zahra Fadilatusya'adah",
      birth: "Metro, 15 February 2003",
      imageUrl: "assets/images/A5/zahra.png",
      instagramUrl: "https://www.instagram.com/fadilazft",
    },

    //IPA 6
    {
      id: 170,
      class: "A6",
      name: "Abid Wujud Putranto",
      birth: "Metro, 8 April 2003",
      imageUrl: "assets/images/A6/abid.png",
      instagramUrl: "https://www.instagram.com/awpisme",
    },
    {
      id: 171,
      class: "A6",
      name: "Alif Rayhan Madani Dalimunthe",
      birth: "Bandung, 31 August 2002",
      imageUrl: "assets/images/A6/alif.png",
      instagramUrl: "https://www.instagram.com/alifrayhanmadanidalimunthe",
    },
    {
      id: 172,
      class: "A6",
      name: "Ambar Gita Soraya Panjaitan",
      birth: "Metro, 22 October 2002",
      imageUrl: "assets/images/A6/ambar.png",
      instagramUrl: "https://www.instagram.com/gitaaasp",
    },
    {
      id: 173,
      class: "A6",
      name: "Andri Muftya Annisa Fitri",
      birth: "Metro, 5 November 2003",
      imageUrl: "assets/images/A6/andri.png",
      instagramUrl: "https://www.instagram.com/andrimuftya",
    },
    {
      id: 174,
      class: "A6",
      name: "Annisa Nur Safitri",
      birth: "Metro, 25 March 2003",
      imageUrl: "assets/images/A6/annisa-n.png",
      instagramUrl: "https://www.instagram.com/annisa.sftri",
    },
    {
      id: 175,
      class: "A6",
      name: "Arneta Diva Ramadhanti Sumantri",
      birth: "Jakarta, 8 November 2002",
      imageUrl: "assets/images/A6/arneta.png",
      instagramUrl: "https://www.instagram.com/netaardrs",
    },
    {
      id: 176,
      class: "A6",
      name: "Bintang Rafi Akbar",
      birth: "Metro, 16 May 2003",
      imageUrl: "assets/images/A6/bintang.png",
      instagramUrl: "https://www.instagram.com/bintangrfkbr",
    },
    {
      id: 177,
      class: "A6",
      name: "Chindy Akila",
      birth: "Pekalongan, 28 May 2003",
      imageUrl: "assets/images/A6/chindy.png",
      instagramUrl: "https://www.instagram.com/chindy_akila28",
    },
    {
      id: 178,
      class: "A6",
      name: "Dhea Putri Ediawati",
      birth: "Pekalongan 2 June 2003",
      imageUrl: "assets/images/A6/dhea.png",
      instagramUrl: "https://www.instagram.com/dheaputri0206",
    },
    {
      id: 179,
      class: "A6",
      name: "Fadhila Husna",
      birth: "Metro, 20 March 2003",
      imageUrl: "assets/images/A6/Fadhila.png",
      instagramUrl: "https://www.instagram.com/fadhilahsn",
    },
    {
      id: 180,
      class: "A6",
      name: "Fajar Rama Adi",
      birth: "Santa Maria, 5 October 2003",
      imageUrl: "assets/images/A6/fajar.png",
      instagramUrl: "https://www.instagram.com/fajarramaadi",
    },
    {
      id: 181,
      class: "A6",
      name: "Grachefa Asyel Rifalia",
      birth: "Metro, 3 April 2003",
      imageUrl: "assets/images/A6/grachefa.png",
      instagramUrl: "https://www.instagram.com/gr.asyelr",
    },
    {
      id: 182,
      class: "A6",
      name: "Idladunna Fitra",
      birth: "Metro, 5 December 2002",
      imageUrl: "assets/images/A6/idladunna.png",
      instagramUrl: "https://www.instagram.com/unnaafs",
    },
    {
      id: 183,
      class: "A6",
      name: "Intan Puspita P.",
      birth: "Metro, 18 January 2003",
      imageUrl: "assets/images/A6/intan.png",
      instagramUrl: "https://www.instagram.com/nat.aaxz",
    },
    {
      id: 184,
      class: "A6",
      name: "Lailatul Mukarromah",
      birth: "Banjarejo, 13 September 2002",
      imageUrl: "assets/images/A6/lailatul.png",
      instagramUrl: "https://www.instagram.com/lailatulela",
    },
    {
      id: 185,
      class: "A6",
      name: "Laura Irinz Regisca",
      birth: "Kartaraharja, 20 February 2003",
      imageUrl: "assets/images/A6/laura.png",
      instagramUrl: "https://www.instagram.com/clauraash",
    },
    {
      id: 186,
      class: "A6",
      name: "Lutfi Khoriun Nisa",
      birth: "Tunas Jaya, 27 April 2003",
      imageUrl: "assets/images/A6/lutfi.png",
      instagramUrl: "https://www.instagram.com/nlutfikhoirun",
    },
    {
      id: 187,
      class: "A6",
      name: "M. Faris Dhaifullah Fatah",
      birth: "Metro, 10 March 2003",
      imageUrl: "assets/images/A6/m-faris.png",
      instagramUrl: "https://www.instagram.com/m.farisdf",
    },
    {
      id: 188,
      class: "A6",
      name: "Msy Kania Setyani Utami",
      birth: "Metro, 12 July 2003",
      imageUrl: "assets/images/A6/msy-kania.png",
      instagramUrl: "https://www.instagram.com/kniayyy_",
    },
    {
      id: 189,
      class: "A6",
      name: "Muhammad Fadly Sentosa",
      birth: "Bogor, 27 February 2003",
      imageUrl: "assets/images/A6/m-fadly.png",
      instagramUrl: "https://www.instagram.com/fadly_sentosa",
    },
    {
      id: 190,
      class: "A6",
      name: "Muhammad Syauki Tarmizi",
      birth: "Metro, 10 January 2004",
      imageUrl: "assets/images/A6/m-syauki.png",
      instagramUrl: "https://www.instagram.com/sykitrmz_",
    },
    {
      id: 191,
      class: "A6",
      name: "Phoenix Bintang Assura",
      birth: "Metro, 24 October 2003",
      imageUrl: "assets/images/A6/phoenix.png",
      instagramUrl: "https://www.instagram.com/",
    },
    {
      id: 192,
      class: "A6",
      name: "Rana Hafizha Ramadhani",
      birth: "Metro, 10 November 2002",
      imageUrl: "assets/images/A6/rana.png",
      instagramUrl: "https://www.instagram.com/ranaazha",
    },
    {
      id: 193,
      class: "A6",
      name: "Rheifani Salsabila Putri",
      birth: "Banjar Agung, 3 November 2003",
      imageUrl: "assets/images/A6/rheifani.png",
      instagramUrl: "https://www.instagram.com/rheifanii",
    },
    {
      id: 194,
      class: "A6",
      name: "Rizqi Lailatul Khairiyyah",
      birth: "Metro, 25 April 2003",
      imageUrl: "assets/images/A6/rizqi.png",
      instagramUrl: "https://www.instagram.com/rizqilailaa",
    },
    {
      id: 195,
      class: "A6",
      name: "Salwa Naqwadisa Madinna",
      birth: "Metro, 26 December 2002",
      imageUrl: "assets/images/A6/salwa.png",
      instagramUrl: "https://www.instagram.com/salwanaqwaa",
    },
    {
      id: 196,
      class: "A6",
      name: "Sasyi Friska Nindiyanti",
      birth: "Pekalongan, 23 November 2002",
      imageUrl: "assets/images/A6/sasyi.png",
      instagramUrl: "https://www.instagram.com/sasyiif",
    },
    {
      id: 197,
      class: "A6",
      name: "Shifa Meilan Pratiwi",
      birth: "Metro, 30 May 2003",
      imageUrl: "assets/images/A6/shifa.png",
      instagramUrl: "https://www.instagram.com/shifameilan",
    },
    {
      id: 198,
      class: "A6",
      name: "Tiara Mustika Rani W.",
      birth: "Metro, 14 April 2003",
      imageUrl: "assets/images/A6/tiara.png",
      instagramUrl: "https://www.instagram.com/twabby",
    },
    {
      id: 199,
      class: "A6",
      name: "Vito Dananjaya",
      birth: "Metro, 4 April 2003",
      imageUrl: "assets/images/A6/vito.png",
      instagramUrl: "https://www.instagram.com/sevenismine",
    },
    {
      id: 200,
      class: "A6",
      name: "Yosi Jawa Tabanendra Kesuma Wardana",
      birth: "Metro, 24 May 2003",
      imageUrl: "assets/images/A6/yosi.png",
      instagramUrl: "https://www.instagram.com/jawa.yosi",
    },
    {
      id: 201,
      class: "A6",
      name: "Zakia Mourice Saraswati",
      birth: "Metro, 2 April 2003",
      imageUrl: "assets/images/A6/zakia.png",
      instagramUrl: "https://www.instagram.com/zakiams_",
    },

    //IPA 7
    {
      id: 202,
      class: "A7",
      name: "A. Rafi Perdana",
      birth: "Metro, 16 May 2003",
      imageUrl: "assets/images/A7/rafi.png",
      instagramUrl: "https://www.instagram.com/arafiperdana",
    },
    {
      id: 203,
      class: "A7",
      name: "Achmad Fajar Primayandi",
      birth: "Metro, 8 June 2003",
      imageUrl: "assets/images/A7/achmad.png",
      instagramUrl: "https://www.instagram.com/achmadfajar03",
    },
    {
      id: 204,
      class: "A7",
      name: "Adib Cahyana Adi",
      birth: "Metro, 15 July 2003",
      imageUrl: "assets/images/A7/adib.png",
      instagramUrl: "https://www.instagram.com/adibcahyanaa",
    },
    {
      id: 205,
      class: "A7",
      name: "Afiqha Rahmati Zauma",
      birth: "Metro, 9 November 2002",
      imageUrl: "assets/images/A7/afiqha.png",
      instagramUrl: "https://www.instagram.com/Afizauma",
    },
    {
      id: 206,
      class: "A7",
      name: "Annisa Jovancka",
      birth: "Metro, 1 April 2003",
      imageUrl: "assets/images/A7/annisa.png",
      instagramUrl: "https://www.instagram.com/ajovancka",
    },
    {
      id: 207,
      class: "A7",
      name: "Atika Indrasari",
      birth: "Metro, 24 April 2003",
      imageUrl: "assets/images/A7/atika.png",
      instagramUrl: "https://www.instagram.com/atikandsr",
    },
    {
      id: 208,
      class: "A7",
      name: "Dafina Nasywa Fiola",
      birth: "Purbolinggo, 23 February 2003",
      imageUrl: "assets/images/A7/dafina.png",
      instagramUrl: "https://www.instagram.com/dafinasywa_",
    },
    {
      id: 209,
      class: "A7",
      name: "Dhimas Maestro",
      birth: "Metro, 11 December 2003",
      imageUrl: "assets/images/A7/dhimas.png",
      instagramUrl: "https://www.instagram.com/dhimas_maestro",
    },
    {
      id: 210,
      class: "A7",
      name: "Diah Ayu Anzarwati",
      birth: "Metro, 25 August 2002",
      imageUrl: "assets/images/A7/diah.png",
      instagramUrl: "https://www.instagram.com/diahayu15_",
    },
    {
      id: 211,
      class: "A7",
      name: "Diva Qaisya Rakhenditya",
      birth: "Klaten, 3 June 2003",
      imageUrl: "assets/images/A7/diva.png",
      instagramUrl: "https://www.instagram.com/divaqaisya",
    },
    {
      id: 212,
      class: "A7",
      name: "Dyah Arum Sekar Kinasih",
      birth: "Metro, 17 September 2003",
      imageUrl: "assets/images/A7/dyah.png",
      instagramUrl: "https://www.instagram.com/",
    },
    {
      id: 213,
      class: "A7",
      name: "Fatha Ariya Prasetya",
      birth: "Metro, 23 February 2003",
      imageUrl: "assets/images/A7/fatha.png",
      instagramUrl: "https://www.instagram.com/fathaarya",
    },
    {
      id: 214,
      class: "A7",
      name: "Fauzan Azi Ramadhani",
      birth: "Metro, 4 December 2002",
      imageUrl: "assets/images/A7/fauzan.png",
      instagramUrl: "https://www.instagram.com/fauzan_dhani",
    },
    {
      id: 215,
      class: "A7",
      name: "Fauzia Azzahra",
      birth: "Metro, 5 June 2003",
      imageUrl: "assets/images/A7/fauzia.png",
      instagramUrl: "https://www.instagram.com/fauzia_azh",
    },
    {
      id: 216,
      class: "A7",
      name: "Igo Muhammad Alvanzo",
      birth: "Metro, 8 April 2003",
      imageUrl: "assets/images/A7/igo.png",
      instagramUrl: "https://www.instagram.com/igoalvanzo",
    },
    {
      id: 217,
      class: "A7",
      name: "Ikram Kusuma Dewanto",
      birth: "Bandar Lampung, 16 October 2003",
      imageUrl: "assets/images/A7/ikram.png",
      instagramUrl: "https://www.instagram.com/kusuma_ikram",
    },
    {
      id: 218,
      class: "A7",
      name: "Indah Ayu Setyarini",
      birth: "Metro, 4 April 2003",
      imageUrl: "assets/images/A7/indah.png",
      instagramUrl: "https://www.instagram.com/iinddaaaahh",
    },
    {
      id: 219,
      class: "A7",
      name: "Junus Tobia Asiando Hutabarat",
      birth: "Metro, 4 November 2003",
      imageUrl: "assets/images/A7/junus.png",
      instagramUrl: "https://www.instagram.com/junustobiaasiando",
    },
    {
      id: 220,
      class: "A7",
      name: "Khairani Al Amanah Az-Zahirah",
      birth: "Bratasena, 4 Juni 2003",
      imageUrl: "assets/images/A7/khairani.png",
      instagramUrl: "https://www.instagram.com/khairaniaaz",
    },
    {
      id: 221,
      class: "A7",
      name: "Khoirun Fahra Della",
      birth: "Metro, 7 August 2002",
      imageUrl: "assets/images/A7/khoirun.png",
      instagramUrl: "https://www.instagram.com/fahradella",
    },
    {
      id: 222,
      class: "A7",
      name: "Kurnia Ramadhan",
      birth: "Metro, 10 November 2002",
      imageUrl: "assets/images/A7/kurnia.png",
      instagramUrl: "https://www.instagram.com/kurniar987",
    },
    {
      id: 223,
      class: "A7",
      name: "Maya Rizki Alfajar",
      birth: "Lambu Kibang, 18 June 2003",
      imageUrl: "assets/images/A7/maya.png",
      instagramUrl: "https://www.instagram.com/",
    },
    {
      id: 224,
      class: "A7",
      name: "M. Rafi Hamdani",
      birth: "Gisting, 14 Januari 2003",
      imageUrl: "assets/images/A7/m-rafi.png",
      instagramUrl: "https://www.instagram.com/rafipatidolken",
    },
    {
      id: 225,
      class: "A7",
      name: "Muhammad Sidiq",
      birth: "Metro, 27 August 2002",
      imageUrl: "assets/images/A7/m-sidiq.png",
      instagramUrl: "https://www.instagram.com/msidiq28",
    },
    {
      id: 226,
      class: "A7",
      name: "Paulo Victory Putrawardanik",
      birth: "Metro, 12 April 2004",
      imageUrl: "assets/images/A7/paulo.png",
      instagramUrl: "https://www.instagram.com/pauvict",
    },
    {
      id: 227,
      class: "A7",
      name: "Ratri Mawas Firdayanti",
      birth: "Metro, 23 March 2003",
      imageUrl: "assets/images/A7/ratri.png",
      instagramUrl: "https://www.instagram.com/duandels",
    },
    {
      id: 228,
      class: "A7",
      name: "Salma Azzahra",
      birth: "Metro, 12 April 2003",
      imageUrl: "assets/images/A7/salma.png",
      instagramUrl: "https://www.instagram.com/",
    },
    {
      id: 229,
      class: "A7",
      name: "Syifa Sekar Ayuning Tyas",
      birth: "Metro, 5 April 2004",
      imageUrl: "assets/images/A7/syifa.png",
      instagramUrl: "https://www.instagram.com/syifasekar_",
    },
    {
      id: 230,
      class: "A7",
      name: "Tegar Hendardityo",
      birth: "Wonosari, 18 October 2002",
      imageUrl: "assets/images/A7/tegar.png",
      instagramUrl: "https://www.instagram.com/hendardityo",
    },
    {
      id: 231,
      class: "A7",
      name: "Theodora Azzahra D.",
      birth: "Brebes, 13 June 2002",
      imageUrl: "assets/images/A7/theodora.png",
      instagramUrl: "https://www.instagram.com/theodora_ara",
    },
    {
      id: 232,
      class: "A7",
      name: "Vincentia Helena Dila",
      birth: "Purwosari, 14 March 2003",
      imageUrl: "assets/images/A7/vincentia.png",
      instagramUrl: "https://www.instagram.com/vincentiahd",
    },
    {
      id: 233,
      class: "A7",
      name: "Widya Ristanda Nurrasyid",
      birth: "Jakarta, 19 April 2003",
      imageUrl: "assets/images/A7/widya.png",
      instagramUrl: "https://www.instagram.com/widyaristanda_",
    },
    {
      id: 234,
      class: "A7",
      name: "Wildan Halim Prasetyo",
      birth: "Metro, 13 April 2003",
      imageUrl: "assets/images/A7/wildan.png",
      instagramUrl: "https://www.instagram.com/wildan_halimp",
    },
    {
      id: 235,
      class: "A7",
      name: "Yehezkiel Pandu Prasetya",
      birth: "Metro, 14 August 2002",
      imageUrl: "assets/images/A7/yehezkiel.png",
      instagramUrl: "https://www.instagram.com/yhzkieelll",
    },

    //IPA 8
    {
      id: 236,
      class: "A8",
      name: "Aisya Sifa Marini Sari",
      birth: "Metro, 20 November 2003",
      imageUrl: "assets/images/A8/aisya.png",
      instagramUrl: "https://www.instagram.com/nimatuyaumul",
    },
    {
      id: 237,
      class: "A8",
      name: "Allamanda Cathartica",
      birth: "Metro, 3 August 2004",
      imageUrl: "assets/images/A8/allamanda.png",
      instagramUrl: "https://www.instagram.com/allamanda.c",
    },
    {
      id: 238,
      class: "A8",
      name: "Allya Khanza Devira",
      birth: "Bukit Kemuning, 12 December 2003",
      imageUrl: "assets/images/A8/allya.png",
      instagramUrl: "https://www.instagram.com/allyakhanza_",
    },
    {
      id: 239,
      class: "A8",
      name: "Alma Karida Anwar",
      birth: "Metro, 2 September 2004",
      imageUrl: "assets/images/A8/alma.png",
      instagramUrl: "https://www.instagram.com/alma.krd",
    },
    {
      id: 240,
      class: "A8",
      name: "Anggun Waliya Salma Hani",
      birth: "Metro, 27 May 2004",
      imageUrl: "assets/images/A8/anggun.png",
      instagramUrl: "https://www.instagram.com/anggun_wasaha",
    },
    {
      id: 241,
      class: "A8",
      name: "Annisa Dwi Erlina",
      birth: "Metro, 23 May 2004",
      imageUrl: "assets/images/A8/annisa-d.png",
      instagramUrl: "https://www.instagram.com/annisazrlna_",
    },
    {
      id: 242,
      class: "A8",
      name: "Annisa Septiarini Mas Gede",
      birth: "Metro, 27 September 2003",
      imageUrl: "assets/images/A8/annisa-s.png",
      instagramUrl: "https://www.instagram.com/annisaseptiarinii",
    },
    {
      id: 243,
      class: "A8",
      name: "Attar Akram Abdillah",
      birth: "Metro, 22 September 2004",
      imageUrl: "assets/images/A8/attar.png",
      instagramUrl: "https://www.instagram.com/a.tar_",
    },
    {
      id: 244,
      class: "A8",
      name: "Bagas Wahyu Pradana",
      birth: "Metro, 13 September 2003",
      imageUrl: "assets/images/A8/bagas.png",
      instagramUrl: "https://www.instagram.com/bgsprdnn",
    },
    {
      id: 245,
      class: "A8",
      name: "Cindy Loria",
      birth: "Pekalongan, 20 May 2004",
      imageUrl: "assets/images/A8/cindy.png",
      instagramUrl: "https://www.instagram.com/cindylo32",
    },
    {
      id: 246,
      class: "A8",
      name: "Dandi Rifqi Caesardo",
      birth: "Metro, 22 March 2004",
      imageUrl: "assets/images/A8/dandi.png",
      instagramUrl: "https://www.instagram.com/caesard0",
    },
    {
      id: 247,
      class: "A8",
      name: "Dendy Elvian Darmansyah",
      birth: "Taman Asri, 21 July 2004",
      imageUrl: "assets/images/A8/dendy.png",
      instagramUrl: "https://www.instagram.com/dendyelvian",
    },
    {
      id: 248,
      class: "A8",
      name: "Elvira Ruth Mahardika Panjaitan",
      birth: "Metro, 11 March 2004",
      imageUrl: "assets/images/A8/elvira.png",
      instagramUrl: "https://www.instagram.com/",
    },
    {
      id: 249,
      class: "A8",
      name: "Faiza Sondang Putri Siagian",
      birth: "Metro, 10 January 2004",
      imageUrl: "assets/images/A8/faiza.png",
      instagramUrl: "https://www.instagram.com/fzasg",
    },
    {
      id: 250,
      class: "A8",
      name: "Falinda Fattah Nindyantika",
      birth: "Ponorogo, 3 September 2003",
      imageUrl: "assets/images/A8/falinda.png",
      instagramUrl: "https://www.instagram.com/flndafttah",
    },
    {
      id: 251,
      class: "A8",
      name: "Ghistavera Izvantia",
      birth: "Metro, 12 October 2003",
      imageUrl: "assets/images/A8/ghistavera.png",
      instagramUrl: "https://www.instagram.com/ghstvia",
    },
    {
      id: 252,
      class: "A8",
      name: "Halmas PrajaHuteba Firanza",
      birth: "Metro, 28 August 2003",
      imageUrl: "assets/images/A8/halmas.png",
      instagramUrl: "https://www.instagram.com/hlms_prfz",
    },
    {
      id: 253,
      class: "A8",
      name: "Inggit Ambarani",
      birth: "Metro, 16 February 2004",
      imageUrl: "assets/images/A8/inggit.png",
      instagramUrl: "https://www.instagram.com/inggit.ambarani_",
    },
    {
      id: 254,
      class: "A8",
      name: "Izqyfa Syafiq Ayasha",
      birth: "Bandar Lampung, 13 Juni 2004",
      imageUrl: "assets/images/A8/izqyfa.png",
      instagramUrl: "https://www.instagram.com/qyfasyaa",
    },
    {
      id: 255,
      class: "A8",
      name: "Jihan Nur Alifia",
      birth: "Metro, 5 May 2004",
      imageUrl: "assets/images/A8/jihan.png",
      instagramUrl: "https://www.instagram.com/jihannalfia",
    },
    {
      id: 256,
      class: "A8",
      name: "Lisa Dwi Aprillia",
      birth: "Tulang Bawang, 13 April 2004",
      imageUrl: "assets/images/A8/lisa.png",
      instagramUrl: "https://www.instagram.com/lisa_apr.13",
    },
    {
      id: 257,
      class: "A8",
      name: "Lusmelia Riyanti",
      birth: "Metro, 25 September 2004",
      imageUrl: "assets/images/A8/lusmelia.png",
      instagramUrl: "https://www.instagram.com/lusmel_lia",
    },
    {
      id: 258,
      class: "A8",
      name: "Made Diksa Pitra",
      birth: "Bandar Lampung, 13 June 2004",
      imageUrl: "assets/images/A8/made-d.png",
      instagramUrl: "https://www.instagram.com/madediksapitra",
    },
    {
      id: 259,
      class: "A8",
      name: "Meiliana Zalianti",
      birth: "Margototo, 22 Mei 2004",
      imageUrl: "assets/images/A8/mailiana.png",
      instagramUrl: "https://www.instagram.com/mailn_zlnt",
    },
    {
      id: 260,
      class: "A8",
      name: "Muhammad Ariq Naufal",
      birth: "Metro, 28 August 2003",
      imageUrl: "assets/images/A8/m-ariq.png",
      instagramUrl: "https://www.instagram.com/ariq_naufal298",
    },
    {
      id: 261,
      class: "A8",
      name: "Muhammad Faris Cahyadi",
      birth: "Metro, 7 July 2004",
      imageUrl: "assets/images/A8/m-faris.png",
      instagramUrl: "https://www.instagram.com/faris_cahyadi",
    },
    {
      id: 262,
      class: "A8",
      name: "Ni'matu Yaumul Laili",
      birth: "Metro, 20 November 2003",
      imageUrl: "assets/images/A8/nimatu.png",
      instagramUrl: "https://www.instagram.com/nimatuyaumul",
    },
    {
      id: 263,
      class: "A8",
      name: "Niluh Cyntia Pratiwi",
      birth: "Bratasena, 3 Juni 2004",
      imageUrl: "assets/images/A8/niluh.png",
      instagramUrl: "https://www.instagram.com/niluhhhhhhh",
    },
    {
      id: 264,
      class: "A8",
      name: "Nur Afni Latifatul Muchlisa",
      birth: "Metro, 18 August 2003",
      imageUrl: "assets/images/A8/nur-afni.png",
      instagramUrl: "https://www.instagram.com/nurafnilm",
    },
    {
      id: 265,
      class: "A8",
      name: "Putri Cahyani Ramadhani",
      birth: "Untoro, 12 November 2004",
      imageUrl: "assets/images/A8/putri.png",
      instagramUrl: "https://www.instagram.com/putricahyani.r",
    },
    {
      id: 266,
      class: "A8",
      name: "Ridwan Hardiansyah",
      birth: "Sumbersari, 3 December 2003",
      imageUrl: "assets/images/A8/ridwan.png",
      instagramUrl: "https://www.instagram.com/ridwanhaar",
    },
    {
      id: 267,
      class: "A8",
      name: "Wafiqoh Maisun Nuha",
      birth: "Metro, 4 December 2003",
      imageUrl: "assets/images/A8/wafiqoh.png",
      instagramUrl: "https://www.instagram.com/mtchajoy",
    },
    {
      id: 268,
      class: "A8",
      name: "Yunita Rahmawani Nasution",
      birth: "Metro, 1 Juni 2004",
      imageUrl: "assets/images/A8/yunita.png",
      instagramUrl: "https://www.instagram.com/yntrhmwn",
    },

    //IPS 1
    {
      id: 269,
      class: "S1",
      name: "Aghil Putra Adhiasti",
      birth: "Sekampung, 3 July 2002",
      imageUrl: "assets/images/S1/aghil.png",
      instagramUrl: "https://www.instagram.com/aghil_adhiasti",
    },
    {
      id: 270,
      class: "S1",
      name: "Ahmad Dani Athallah",
      birth: "Metro, 18 November 2002",
      imageUrl: "assets/images/S1/ahmad.png",
      instagramUrl: "https://www.instagram.com/adaniathallah",
    },
    {
      id: 271,
      class: "S1",
      name: "Andre Samuel Togatorop",
      birth: "Metro, 12 July 2003",
      imageUrl: "assets/images/S1/andre.png",
      instagramUrl: "https://www.instagram.com/ndresamm",
    },
    {
      id: 272,
      class: "S1",
      name: "Annisa Nur Hidayah",
      birth: "Metro, 7 September 2002",
      imageUrl: "assets/images/S1/annisa.png",
      instagramUrl: "https://www.instagram.com/annisa.nh79",
    },
    {
      id: 273,
      class: "S1",
      name: "Arfian Faiq Hibatullah",
      birth: "Metro, 9 May 2003",
      imageUrl: "assets/images/S1/arfian.png",
      instagramUrl: "https://www.instagram.com/masfaiqqq",
    },
    {
      id: 274,
      class: "S1",
      name: "Arief Wicaksono",
      birth: "Metro, 7 September 2003",
      imageUrl: "assets/images/S1/arief.png",
      instagramUrl: "https://www.instagram.com/ariefwicaksn",
    },
    {
      id: 275,
      class: "S1",
      name: "Auly Pradina",
      birth: "Lampung Tengah, 20 August 2002",
      imageUrl: "assets/images/S1/auly.png",
      instagramUrl: "https://www.instagram.com/dinapradn",
    },
    {
      id: 276,
      class: "S1",
      name: "Bagas Satria Wijaya",
      birth: "Metro, 11 December 2003",
      imageUrl: "assets/images/S1/bagas.png",
      instagramUrl: "https://www.instagram.com/bgstrwjya",
    },
    {
      id: 277,
      class: "S1",
      name: "Bagus Febrianfah Sanrio",
      birth: "Metro, 17 February 2003",
      imageUrl: "assets/images/S1/bagus.png",
      instagramUrl: "https://www.instagram.com/bagus.fs123",
    },
    {
      id: 278,
      class: "S1",
      name: "Benny Hamdani Halim",
      birth: "Pekalongan, 29 June 2003",
      imageUrl: "assets/images/S1/benny.png",
      instagramUrl: "https://www.instagram.com/benny_melek",
    },
    {
      id: 279,
      class: "S1",
      name: "Christina Dini Anggraini",
      birth: "Metro, 14 July 2003",
      imageUrl: "assets/images/S1/christina.png",
      instagramUrl: "https://www.instagram.com/christinadini",
    },
    {
      id: 280,
      class: "S1",
      name: "Dimas Putra Arviska",
      birth: "Adirejo, 28 December 2002",
      imageUrl: "assets/images/S1/dimas.png",
      instagramUrl: "https://www.instagram.com/dimasptrrrrr",
    },
    {
      id: 281,
      class: "S1",
      name: "Fadhila Khairun Nisa",
      birth: "Metro, 10 December 2002",
      imageUrl: "assets/images/S1/fadhila.png",
      instagramUrl: "https://www.instagram.com/fadhilakn_",
    },
    {
      id: 282,
      class: "S1",
      name: "Hafizd Zikri",
      birth: "Metro, 10 January 2003",
      imageUrl: "assets/images/S1/hafizd.png",
      instagramUrl: "https://www.instagram.com/hafizdzkr",
    },
    {
      id: 283,
      class: "S1",
      name: "Hanif Dinanda Putra",
      birth: "Metro, 30 November 2002",
      imageUrl: "assets/images/S1/hanif.png",
      instagramUrl: "https://www.instagram.com/dinandaptra",
    },
    {
      id: 284,
      class: "S1",
      name: "Hanifah Khoirunnisa",
      birth: "Kecubung, 5 September 2002",
      imageUrl: "assets/images/S1/hanifah.png",
      instagramUrl: "https://www.instagram.com/hanifah.khn",
    },
    {
      id: 285,
      class: "S1",
      name: "Iqbal Al Hakim",
      birth: "Metro, 17 September 2003",
      imageUrl: "assets/images/S1/iqbal.png",
      instagramUrl: "https://www.instagram.com/iqbal.alhkm",
    },
    {
      id: 286,
      class: "S1",
      name: "Leonardo Sander",
      birth: "Metro, 5 September 2002",
      imageUrl: "assets/images/S1/leonardo.png",
      instagramUrl: "https://www.instagram.com/leonardosander13",
    },
    {
      id: 287,
      class: "S1",
      name: "Luna Azzahra",
      birth: "Cileungsi, 6 October 2003",
      imageUrl: "assets/images/S1/luna.png",
      instagramUrl: "https://www.instagram.com/lunaazzahra",
    },
    {
      id: 288,
      class: "S1",
      name: "Lutfia Munisa A.",
      birth: "Metro, 8 April 2003",
      imageUrl: "assets/images/S1/lutfia.png",
      instagramUrl: "https://www.instagram.com/lutfiamns",
    },
    {
      id: 289,
      class: "S1",
      name: "Maharani Suci Aprilia",
      birth: "Metro, 24 April 2003",
      imageUrl: "assets/images/S1/maharani.png",
      instagramUrl: "https://www.instagram.com/aprlsucii_",
    },
    {
      id: 290,
      class: "S1",
      name: "Marcellus Arya Bimantaka",
      birth: "Metro, 7 October 2002",
      imageUrl: "assets/images/S1/marcellus.png",
      instagramUrl: "https://www.instagram.com/mamar.cel",
    },
    {
      id: 291,
      class: "S1",
      name: "Marciano Elia Waworuntu",
      birth: "Jakarta, 29 October 2003",
      imageUrl: "assets/images/S1/marciano.png",
      instagramUrl: "https://www.instagram.com/marcn.ell",
    },
    {
      id: 292,
      class: "S1",
      name: "Michael Jagger Yani",
      birth: "Metro, 23 February 2003",
      imageUrl: "assets/images/S1/michael.png",
      instagramUrl: "https://www.instagram.com/x.mjy.x",
    },
    {
      id: 293,
      class: "S1",
      name: "Mutiara Nufus",
      birth: "Metro, 1 September 2003",
      imageUrl: "assets/images/S1/mutiara-n.png",
      instagramUrl: "https://www.instagram.com/mutiaranufus",
    },
    {
      id: 294,
      class: "S1",
      name: "Mutiara Prishanti",
      birth: "Metro, 3 April 2003",
      imageUrl: "assets/images/S1/mutiara-p.png",
      instagramUrl: "https://www.instagram.com/mtiraprshnti_",
    },
    {
      id: 295,
      class: "S1",
      name: "Nabila Yulia Nurhaliza",
      birth: "Metro, 18 July 2003",
      imageUrl: "assets/images/S1/nabila.png",
      instagramUrl: "https://www.instagram.com/nabila.ynn",
    },
    {
      id: 296,
      class: "S1",
      name: "Olanasia Kholifatul Jannah",
      birth: "Nampirejo, 19 October 2002",
      imageUrl: "assets/images/S1/olanasia.png",
      instagramUrl: "https://www.instagram.com/olanasiakh",
    },
    {
      id: 297,
      class: "S1",
      name: "Putri Ayu Anggira",
      birth: "Teluk Betung, 8 September 2003",
      imageUrl: "assets/images/S1/putri.png",
      instagramUrl: "https://www.instagram.com/putrianggiraa",
    },
    {
      id: 298,
      class: "S1",
      name: "Rayhan Thabit Ramadhan Sesunan",
      birth: "Jakarta, 11 November 2003",
      imageUrl: "assets/images/S1/rayhan.png",
      instagramUrl: "https://www.instagram.com/rayhanthbt",
    },
    {
      id: 299,
      class: "S1",
      name: "Ristia Salsabila",
      birth: "Adirejo, 4 August 2003",
      imageUrl: "assets/images/S1/ristia.png",
      instagramUrl: "https://www.instagram.com/ristia_slsaa",
    },
    {
      id: 300,
      class: "S1",
      name: "Rizqa Setia Wardhani",
      birth: "Pekalongan, 28 July 2002",
      imageUrl: "assets/images/S1/rizqa.png",
      instagramUrl: "https://www.instagram.com/rizqasetiaw_",
    },
    {
      id: 301,
      class: "S1",
      name: "Shofiyyah Rozanah",
      birth: "Metro, 20 December 2001",
      imageUrl: "assets/images/S1/shofiyyah.png",
      instagramUrl: "https://www.instagram.com/shhhrrmm",
    },
    {
      id: 302,
      class: "S1",
      name: "Tiara Hermala",
      birth: "Metro, 13 August 2002",
      imageUrl: "assets/images/S1/tiara.png",
      instagramUrl: "https://www.instagram.com/tiara_hrn",
    },
    {
      id: 303,
      class: "S1",
      name: "Yohana Indah Noventina",
      birth: "Metro, 14 November 2002",
      imageUrl: "assets/images/S1/yohana.png",
      instagramUrl: "https://www.instagram.com/yohna_indh",
    },

    // IPS 2
    {
      id: 304,
      class: "S2",
      name: "Adisya Fadilah Azzahra",
      birth: "Pekalongan, 8 May 2003",
      imageUrl: "assets/images/S2/adisya.png",
      instagramUrl: "https://www.instagram.com/adisyazhr",
    },
    {
      id: 305,
      class: "S2",
      name: "Agatha Fabianabel Artha Wiguna",
      birth: "Metro, 11 August 2003",
      imageUrl: "assets/images/S2/agatha.png",
      instagramUrl: "https://www.instagram.com/agathaabel_",
    },
    {
      id: 306,
      class: "S2",
      name: "Ahmad Raihan Rony",
      birth: "Metro, 18 April 2003",
      imageUrl: "assets/images/S2/ahmad.png",
      instagramUrl: "https://www.instagram.com/a_r_r_0_4",
    },
    {
      id: 307,
      class: "S2",
      name: "Akbar Dika",
      birth: "Margajaya, 17 August 2002",
      imageUrl: "assets/images/S2/akbar.png",
      instagramUrl: "https://www.instagram.com/akbar17dika",
    },
    {
      id: 308,
      class: "S2",
      name: "Alfonsus Fribuyan Riswara",
      birth: "Metro, 10 January 2003",
      imageUrl: "assets/images/S2/alfonsus.png",
      instagramUrl: "https://www.instagram.com/alforiswara",
    },
    {
      id: 309,
      class: "S2",
      name: "Amanda Miat Kurnia",
      birth: "Suka Jaya, 25 December 2002",
      imageUrl: "assets/images/S2/amanda.png",
      instagramUrl: "https://www.instagram.com/amndmita_",
    },
    {
      id: 310,
      class: "S2",
      name: "Anisa Latifah Rahman Lubis",
      birth: "Bandar Jaya, 11 March 2003",
      imageUrl: "assets/images/S2/anisa.png",
      instagramUrl: "https://www.instagram.com/lubiiis",
    },
    {
      id: 311,
      class: "S2",
      name: "Arrow Akbar Sonjaya Munfit",
      birth: "Metro, 5 January 2003",
      imageUrl: "assets/images/S2/arrow.png",
      instagramUrl: "https://www.instagram.com/arrowakbar_",
    },
    {
      id: 312,
      class: "S2",
      name: "Auddy Fortuna Azzahra",
      birth: "Metro, 9 November 2003",
      imageUrl: "assets/images/S2/auddy.png",
      instagramUrl: "https://www.instagram.com/auddyazzahra",
    },
    {
      id: 313,
      class: "S2",
      name: "Della Putriani Rusadi",
      birth: "Metro, 7 September 2003",
      imageUrl: "assets/images/S2/della.png",
      instagramUrl: "https://www.instagram.com/dellaptrrsd",
    },
    {
      id: 314,
      class: "S2",
      name: "Dionisius Bayu Ari Laksono",
      birth: "Metro, 1 December 2002",
      imageUrl: "assets/images/S2/dionisius.png",
      instagramUrl: "https://www.instagram.com/bayuarie90",
    },
    {
      id: 315,
      class: "S2",
      name: "Diovano Danendra",
      birth: "Metro, 30 December 2002",
      imageUrl: "assets/images/S2/diovano.png",
      instagramUrl: "https://www.instagram.com/diovanodnra",
    },
    {
      id: 316,
      class: "S2",
      name: "Fadhlan Permata Aji",
      birth: "Metro, 30 October 2002",
      imageUrl: "assets/images/S2/fadhlan.png",
      instagramUrl: "https://www.instagram.com/fadhlanpermataaji",
    },
    {
      id: 317,
      class: "S2",
      name: "Fern Vallenshea",
      birth: "Siraman, 2 February 2003",
      imageUrl: "assets/images/S2/fern.png",
      instagramUrl: "https://www.instagram.com/fern_vallenshea",
    },
    {
      id: 318,
      class: "S2",
      name: "Fianda Metha Jasnika",
      birth: "Pekanbaru, 3 January 2003",
      imageUrl: "assets/images/S2/fianda.png",
      instagramUrl: "https://www.instagram.com/methajasnika",
    },
    {
      id: 319,
      class: "S2",
      name: "Ghina Cahayani",
      birth: "Metro, 8 January 2003",
      imageUrl: "assets/images/S2/ghina.png",
      instagramUrl: "https://www.instagram.com/cahyanighina",
    },
    {
      id: 320,
      class: "S2",
      name: "Halmas Firanzi",
      birth: "Metro, 14 July 2002",
      imageUrl: "assets/images/S2/halmas.png",
      instagramUrl: "https://www.instagram.com/halmasfiranzi_",
    },
    {
      id: 321,
      class: "S2",
      name: "Jeny Alvita Nada",
      birth: "Metro, 18 January 2003",
      imageUrl: "assets/images/S2/jeny.png",
      instagramUrl: "https://www.instagram.com/jenynada_",
    },
    {
      id: 322,
      class: "S2",
      name: "Laras Prasasti",
      birth: "Pekalongan, 16 March 2003",
      imageUrl: "assets/images/S2/laras.png",
      instagramUrl: "https://www.instagram.com/ayaswoo",
    },
    {
      id: 323,
      class: "S2",
      name: "Lusi Febrianti",
      birth: "Metro, 18 February",
      imageUrl: "assets/images/S2/lusi.png",
      instagramUrl: "https://www.instagram.com/f_lusi07",
    },
    {
      id: 324,
      class: "S2",
      name: "M. Arva Zada S.",
      birth: "Metro, 21 May 2003",
      imageUrl: "assets/images/S2/m-arva.png",
      instagramUrl: "https://www.instagram.com/marvazadas_",
    },
    {
      id: 325,
      class: "S2",
      name: "Marshelina Andrea",
      birth: "Metro, 30 Juni 2002",
      imageUrl: "assets/images/S2/marshelina.png",
      instagramUrl: "https://www.instagram.com/marshel_andrea",
    },
    {
      id: 326,
      class: "S2",
      name: "Maura Balqis Ellestifani",
      birth: "Metro, 28 Mei 2003",
      imageUrl: "assets/images/S2/maura.png",
      instagramUrl: "https://www.instagram.com/maurabalqisef",
    },
    {
      id: 327,
      class: "S2",
      name: "Muhammad Rizky Prasetya",
      birth: "Metro, 25 August 2003",
      imageUrl: "assets/images/S2/m-rizky.png",
      instagramUrl: "https://www.instagram.com/m_rizky_pr",
    },
    {
      id: 328,
      class: "S2",
      name: "Muhammad Tito Adhi Prakosa",
      birth: "Lampung Timur, 10 Desember 2002",
      imageUrl: "assets/images/S2/m-tito.png",
      instagramUrl: "https://www.instagram.com/muhammadtito114",
    },
    {
      id: 329,
      class: "S2",
      name: "Mutia Fisabilla Widoyopi",
      birth: "Metro, 20 January 2003",
      imageUrl: "assets/images/S2/mutia.png",
      instagramUrl: "https://www.instagram.com/mutiaaafw",
    },
    {
      id: 330,
      class: "S2",
      name: "Niki Sasi Kirani",
      birth: "Metro, 24 February 2003",
      imageUrl: "assets/images/S2/niki.png",
      instagramUrl: "https://www.instagram.com/nikisasi",
    },
    {
      id: 331,
      class: "S2",
      name: "Novrizal Saputra",
      birth: "Ciamis, 2 November 2002",
      imageUrl: "assets/images/S2/novrizal.png",
      instagramUrl: "https://www.instagram.com/novrizal.saputra",
    },
    {
      id: 332,
      class: "S2",
      name: "Nurico Mareza Kelana",
      birth: "Jakarta, 20 March 2004",
      imageUrl: "assets/images/S2/nurico.png",
      instagramUrl: "https://www.instagram.com/ricomarezaa",
    },
    {
      id: 333,
      class: "S2",
      name: "Rifqi Nazhir Halim",
      birth: "Metro, 25 September 2003",
      imageUrl: "assets/images/S2/rifqi.png",
      instagramUrl: "https://www.instagram.com/rifqi.lim",
    },
    {
      id: 334,
      class: "S2",
      name: "Risma Anggita Cahyani",
      birth: "Raman Utara, 18 October 2002",
      imageUrl: "assets/images/S2/risma.png",
      instagramUrl: "https://www.instagram.com/rismaagta",
    },
    {
      id: 335,
      class: "S2",
      name: "Shazkya Putri Devania",
      birth: "Metro, 28 October 2002",
      imageUrl: "assets/images/S2/shazkya.png",
      instagramUrl: "https://www.instagram.com/shazkya_putrii",
    },
    {
      id: 336,
      class: "S2",
      name: "Vinsi Violita",
      birth: "Pekalongan, 25 Mei 2003",
      imageUrl: "assets/images/S2/vinsi.png",
      instagramUrl: "https://www.instagram.com/vinsivio25",
    },
    {
      id: 337,
      class: "S2",
      name: "Wayan Jordi Rage A. M.",
      birth: "Siswo Bangun, 2 February 2002",
      imageUrl: "assets/images/S2/wayan.png",
      instagramUrl: "https://www.instagram.com/wayanjordi123",
    },
  ];
};

export { getStudentsData, classPhotoData };
